[project]
name = "clarinet"
requirements = []

[contracts.simple-counter]
path = "contracts/simple-counter.clar"
depends_on = []

[contracts.sip-10-ft-standard]
path = "contracts/sip-10-ft-standard.clar"
depends_on = []

[contracts.counter-coin]
path = "contracts/counter-coin.clar"
depends_on = ["sip-10-ft-standard"]

[contracts.counter]
path = "contracts/counter.clar"
depends_on = ["counter-coin"]
