version: '3.7'
services:
  bitcoind:
    image: blockstack/bitcoind:puppet-chain
    container_name: bitcoin
    restart: on-failure
    volumes:
      - ./provisioning/puppet-bitcoin:/etc/bitcoin
    expose:
      - 18443
      - 28444
    environment:
      - DYNAMIC_GENESIS_TIMESTAMP=1
      - RUST_BACKTRACE=1
    networks:
      - localnet

  bitcoind-createwallet:
    image: byrnedo/alpine-curl
    depends_on:
    
      - bitcoind
    restart: on-failure
    command: |
      -f -u blockstack:blockstack --data-binary '{"jsonrpc": "1.0", "id": "c", "method": "createwallet", "params": ["testwallet"]}' -H 'content-type: text/plain;' http://bitcoind:18443
    networks:
      - localnet

  bitcoind-fill-faucet:
    image: byrnedo/alpine-curl
    depends_on:
      - bitcoind
    restart: on-failure
    command: |
      -f -u blockstack:blockstack --data-binary '{"jsonrpc": "1.0", "id":"c", "method": "generatetoaddress", "params": [110, "mrzLDS7LT3otAnpiRWGYkWipdnAZJaXAZQ"] }' -H 'content-type: text/plain;' http://bitcoind:18443
    networks:
      - localnet

  postgres:
    container_name: postgres
    image: "postgres:12.2"
    ports:
      - "5490:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stacks_blockchain_api
      POSTGRES_PORT: 5432
    networks:
      - localnet

  stacks-leader:
    container_name: stacks-leader
    build:
      context: ./provisioning/stacks-blockchain
    command: stacks-node start --config=/app/config/leader-conf.toml
    restart: on-failure
    environment:
      XBLOCKSTACK_DEBUG: 1
      RUST_BACKTRACE: 1
    ports:
      - "20443:20443"
      - "20444:20444"
    volumes:
      - ./configuration/local/:/app/config
      - ./volumes/localnet/stacks-blockchain/leader:/tmp/stacks-blockchain-data
    networks:
      - localnet

  stacks-follower:
    container_name: stacks-follower
    build:
      context: ./provisioning/stacks-blockchain
    command: stacks-node start --config=/app/config/follower-conf.toml
    restart: on-failure
    environment:
      STACKS_EVENT_OBSERVER: stacks-blockchain-api:3700
      XBLOCKSTACK_DEBUG: 1
      RUST_BACKTRACE: 1
    ports:
      - "30443:30443"
      - "30444:30444"
    volumes:
      - ./configuration/local/:/app/config
      - ./volumes/localnet/stacks-blockchain/follower:/tmp/stacks-blockchain-data
    networks:
      - localnet

  stacks-blockchain-api:
    container_name: stacks-blockchain-api
    image: blockstack/stacks-blockchain-api:latest
    restart: on-failure
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: stacks_blockchain_api
      STACKS_CORE_EVENT_PORT: 3700
      STACKS_CORE_EVENT_HOST: http://0.0.0.0
      STACKS_BLOCKCHAIN_API_PORT: 3999
      STACKS_BLOCKCHAIN_API_HOST: 0.0.0.0
      STACKS_BLOCKCHAIN_API_DB: pg
      STACKS_CORE_RPC_HOST: stacks-leader
      STACKS_CORE_RPC_PORT: 20443
      NODE_ENV: development
      STACKS_CHAIN_ID: 2147483648
    ports:
      - "3999:3999"
      - "9153:9153"
    volumes:
      - ./volumes/localnet/stacks-blockchain-api/:/app/config
    depends_on: 
      - postgres
    networks:
      - localnet

networks:
  localnet:
