version: '3.7'
services:
  bitcoind:
    build:
      context: ./provisioning/bitcoin
    ports:
      - "18443:18443"
      - "18444:18444"
    command: 
      -chain=regtest
      -disablewallet=0
      -printtoconsole
      -txindex=1
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=blockstack
      -rpcpassword=blockstack
    networks:
      - mocknet

  bitcoind-fill-faucet:
    image: byrnedo/alpine-curl
    depends_on:
      - bitcoind
    restart: on-failure
    command: |
      -f -u blockstack:blockstack --data-binary '{"jsonrpc": "1.0", "id":"c", "method": "generatetoaddress", "params": [110, "mrzLDS7LT3otAnpiRWGYkWipdnAZJaXAZQ"] }' -H 'content-type: text/plain;' http://bitcoind:18443
    networks:
      - mocknet

  bitcoind-createwallet:
    image: byrnedo/alpine-curl
    depends_on:
      - bitcoind
    restart: on-failure
    command: |
      -f -u blockstack:blockstack --data-binary '{"jsonrpc": "1.0", "id": "curltest", "method": "createwallet", "params": ["testwallet"]}' -H 'content-type: text/plain;' http://bitcoind:18443
    networks:
      - mocknet

  postgres:
    image: "postgres:12.2"
    ports:
      - "5490:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stacks_blockchain_api
      POSTGRES_PORT: 5432
    networks:
      - mocknet

  stacks-blockchain:
    build:
      context: ./provisioning/stacks-blockchain
    command: stacks-node start --config=/app/config/config.toml
    restart: on-failure
    environment:
      STACKS_EVENT_OBSERVER: stacks-blockchain-api:3700
      XBLOCKSTACK_DEBUG: 1
      RUST_BACKTRACE: 1
    ports:
      - "20443:20443"
      - "20444:20444"
    volumes:
      - ./configuration/mocknet/:/app/config
      - ./volumes/mocknet/stacks-blockchain:/tmp/stacks-blockchain-data
    networks:
      - mocknet
    depends_on:
      - bitcoind-fill-faucet
  
  explorer:
    image: blockstack/explorer
    container_name: explorer
    environment:
      - MOCKNET_API_SERVER=http://localhost:3999
    ports:
      - 3000:3000
    networks:
      - mocknet
    depends_on: 
      - stacks-blockchain-api
  
  stacks-blockchain-api:
    image: blockstack/stacks-blockchain-api:latest
    restart: on-failure
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: stacks_blockchain_api
      STACKS_CORE_EVENT_PORT: 3700
      STACKS_CORE_EVENT_HOST: http://0.0.0.0
      STACKS_BLOCKCHAIN_API_PORT: 3999
      STACKS_BLOCKCHAIN_API_HOST: 0.0.0.0
      STACKS_BLOCKCHAIN_API_DB: pg
      STACKS_CORE_RPC_HOST: stacks-blockchain
      STACKS_CORE_RPC_PORT: 20443
      NODE_ENV: development
      STACKS_CHAIN_ID: 0x80000000
    ports:
      - "3999:3999"
      - "9153:9153"
    volumes:
      - ./stacks-blockchain/:/app/config
    networks:
      - mocknet
    depends_on: 
      - postgres

networks:
  mocknet:
